AWSTemplateFormatVersion: 2010-09-09
Description: "CloudTrail Integration for QRadar. (abp-1kirFQBF75MfEQ3RbMQHRb-42uebFeAkVOI7f1QU0xH7b-ln88tcpg)"

Parameters:
  pSRASourceS3BucketName:
    AllowedPattern: '^([\w.-]{1,900})$|^(\/[\w.-]{1,900})*[\w.-]{1,900}$'
    ConstraintDescription: Must be alphanumeric or special characters [., _, -]. In addition, the slash character ( / ) used to delineate hierarchies in parameter names.
    Default: aws-abi
    Description: Source bucket for all templates and artefacts that will get copied into staging bucket
    Type: String
  pSRAS3BucketRegion:
    AllowedPattern: ^[a-z][a-z]-[a-z]*-[0-9]*$
    Type: String
    Default: us-east-1
  pSRAStagingS3KeyPrefix:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    Type: String
    Default: cfn-abi-ibmsecurity-qradar
  pCloudTrailQueueName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    Type: String
    Default: qradar-cloudtrail-queue
  pCloudTrailLambdaFunctionName:
    AllowedPattern: '^[\w-]{1,64}$'
    ConstraintDescription: Max 64 alphanumeric characters. Also special characters supported [_, -]
    Default: sra-ct-s3
    Description: Lambda function name for CloudTrail S3 Event Notification Configuration
    Type: String
  pCloudTrailLambdaRoleName:
    AllowedPattern: '^[\w+=,.@-]{1,64}$'
    ConstraintDescription: Max 64 alphanumeric characters. Also special characters supported [+, =, ., @, -].
    Default: sra-ct-s3-lambda
    Description: Lambda execution role for CloudTrail S3 Event Notification Configuration
    Type: String
  pRepoURL:
    Default: "https://github.com/aws-samples/aws-security-reference-architecture-examples.git"
    Description: AWS Security Reference Architecture examples repository URL
    Type: String
  pRepoBranch:
    Default: "tags/v3.0.4"
    Description: SRA version to tag
    Type: String
  pControlTower:
    AllowedValues: ['true', 'false']
    Default: 'true'
    Description:
      Indicates whether AWS Control Tower is deployed and being used for this AWS environment.
    Type: String
  pSecurityAccountId:
    AllowedPattern: '^\d{12}$'
    Default: 111111111111
    ConstraintDescription: Must be 12 digits.
    Description: AWS Account ID of the Security Tooling account (ignored for AWS Control Tower environments).
    Type: String
  pLogArchiveAccountId:
    AllowedPattern: '^\d{12}$'
    Default: 222222222222
    ConstraintDescription: Must be 12 digits.
    Description: AWS Account ID of the Log Archive account (ignored for AWS Control Tower environments).
    Type: String
  pGovernedRegions:
    AllowedPattern: '^(ct-regions)|((\b(?<!@)(af-south-1|ap-east-1|ap-northeast-1|ap-northeast-2|ap-northeast-3|ap-south-1|ap-south-2|ap-southeast-1|ap-southeast-2|ap-southeast-3|ap-southeast-4|ca-central-1|cn-north-1|cn-northwest-1|eu-central-1|eu-central-2|eu-north-1|eu-south-1|eu-south-2|eu-west-1|eu-west-2|eu-west-3|me-central-1|me-south-1|sa-east-1|us-east-1|us-east-2|us-gov-east-1|us-gov-west-1|us-west-1|us-west-2)\b,{0,1})*)$'
    ConstraintDescription:
      For AWS Control Tower, set to ct-regions (default).  If not using AWS Control Tower, specify comma separated list of regions (e.g. us-west-2,us-east-1,ap-south-1) in lower case.
    Default: ct-regions
    Description: AWS regions (comma separated) if not using AWS Control Tower (leave set to ct-regions for AWS Control Tower environments)
    Type: String
  pCreateAWSControlTowerExecutionRole:
    AllowedValues: ['true', 'false']
    Default: 'true'
    Description: Indicates whether the AWSControlTowerExecution role should be created in the management account. (Only when AWS Control Tower landing zone is deployed. The 'pControlTower' must be set to 'true')
    Type: String
  pAdminRoleName:
    Default: 'AWSCloudFormationStackSetAdministrationRole'
    Description: IAM role in the Management account, used to deploy stacks in other account/regions. Needed only when 'pControlTower' is set to 'false'
    Type: String
  pExecRoleName:
    Default: 'AWSCloudFormationStackSetExecutionRole'
    Description: IAM role in the AWS accounts, which allows trusted access to 'pAdminRoleName'. Needed only when 'pControlTower' is set to 'false'
    Type: String

Conditions:
  cControlTowerEnabled: !Equals [!Ref pControlTower, 'true']

Resources:
  CloudTrailStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub >-
        https://${pSRASourceS3BucketName}.s3.${pSRAS3BucketRegion}.${AWS::URLSuffix}/${pSRAStagingS3KeyPrefix}/submodules/aws-security-reference-architecture-examples/aws_sra_examples/modules/cloudtrail-org-module/templates/sra-cloudtrail-org-module-main.yaml
      Parameters:
        pRepoURL: !Ref pRepoURL
        pRepoBranch: !Ref pRepoBranch
        pEnableDataEventsOnly: 'false'
        pEnableLambdaDataEvents: 'false'
        pEnableS3DataEvents: 'true'
        pCreateAWSControlTowerExecutionRole: !Ref pCreateAWSControlTowerExecutionRole
        pControlTower: !Ref pControlTower
        pGovernedRegions: !Ref pGovernedRegions
        pSecurityAccountId: !Ref pSecurityAccountId
        pLogArchiveAccountId: !Ref pLogArchiveAccountId
      Tags:
        - Key: sra-solution
          Value: !Ref pSRAStagingS3KeyPrefix

  CloudTrailEventListenerStackSet:
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: qradar-cloudtrail-event-stack
      AdministrationRoleARN: !If 
          - cControlTowerEnabled
          - !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:role/service-role/AWSControlTowerStackSetRole
          - !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:role/${pAdminRoleName}
      CallAs: SELF
      Description: Enabled S3 Bucket Event Listener to Send CloudTrail Messages to SQS
      ExecutionRoleName: !If
          - cControlTowerEnabled
          - 'AWSControlTowerExecution'
          - !Ref pExecRoleName
      Capabilities:
        - CAPABILITY_NAMED_IAM
      ManagedExecution:
        Active: true
      OperationPreferences:
        FailureTolerancePercentage: 0
        MaxConcurrentPercentage: 100
        RegionConcurrencyType: PARALLEL
      PermissionModel: SELF_MANAGED
      StackInstancesGroup:
        - DeploymentTargets:
            Accounts:
              - !GetAtt [CloudTrailStack, Outputs.oLogArchiveAccountId]
          Regions:
            - !Ref AWS::Region
      TemplateURL: !Sub https://${pSRASourceS3BucketName}.s3.${pSRAS3BucketRegion}.${AWS::URLSuffix}/${pSRAStagingS3KeyPrefix}/templates/enable-integrations/enable-sqs-s3-integrations.yaml
      Parameters:
        - ParameterKey: pQueueName
          ParameterValue: !Ref pCloudTrailQueueName
        - ParameterKey: pBucketName
          ParameterValue: !GetAtt
            - CloudTrailStack
            - Outputs.oOrganizationCloudTrailS3BucketName
        - ParameterKey: pBucketArn
          ParameterValue: !GetAtt
            - CloudTrailStack
            - Outputs.oOrganizationCloudTrailS3BucketArn
        - ParameterKey: pLambdaFunctionName
          ParameterValue: !Ref pCloudTrailLambdaFunctionName
        - ParameterKey: pLambdaRoleName
          ParameterValue: !Ref pCloudTrailLambdaRoleName
      Tags:
        - Key: sra-solution
          Value: !Ref pSRAStagingS3KeyPrefix

Outputs:
  oOrganizationCloudTrailS3BucketName:
    Description: Organization CloudTrail S3 Bucket Name
    Value:
      !GetAtt [CloudTrailStack, Outputs.oOrganizationCloudTrailS3BucketName]
  oOrganizationCloudTrailS3BucketArn:
    Description: Organization CloudTrail S3 Bucket Arn
    Value: !GetAtt [CloudTrailStack, Outputs.oOrganizationCloudTrailS3BucketArn]
  oManagementAccountId:
    Description: Management Account ID
    Value: !GetAtt [CloudTrailStack, Outputs.oManagementAccountId]
  oLogArchiveAccountId:
    Description: Log Archive Account ID
    Value: !GetAtt [CloudTrailStack, Outputs.oLogArchiveAccountId]
  oAuditAccountId:
    Description: Audit Account ID
    Value: !GetAtt [CloudTrailStack, Outputs.oAuditAccountId]
  oCloudTrailSQSQueueURL:
    Description: 'SQS URL for the CloudTrail events'
    Value: !Sub 'https://sqs.${AWS::Region}.amazonaws.com/${CloudTrailStack.Outputs.oLogArchiveAccountId}/${pCloudTrailQueueName}'
  oCloudTrailSQSQueueName:
    Description: 'SQS Name for the CloudTrail events'
    Value: !Ref pCloudTrailQueueName
  oCloudTrailSQSQueueArn:
    Description: 'Arn for the CloudTrail events queue'
    Value: !Sub 'arn:aws:sqs:${AWS::Region}:${CloudTrailStack.Outputs.oLogArchiveAccountId}:${pCloudTrailQueueName}'
